PERIPHERALS = pwm pit adc

DRIVERS = led pacer usb_serial rf ledtape

TARGET = pwm_test2.bin

SRC = pwm_test2.c
INCLUDES += -I../../apps/common
SRC += ../../apps/common/common.c

include ../../boards/board.mk



